import imghdr
import smtplib
import time

import openpyxl as xl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

count = 0
username = str('snb.khurram@gmail.com')
password = str('khurramsaeed03360736736')
From = username
Subject = 'Farrier Tools & Veterinary Instruments Manufacturing Company'

wb = xl.load_workbook(r'C:\Users\skt\Documents\emailer.xlsx')
sheet1 = wb.get_sheet_by_name('Sheet1')

names = []
emails = []

for cell in sheet1['A']:
    emails.append(cell.value)

for cell in sheet1['B']:
    names.append(cell.value)

server = smtplib.SMTP('smtp.gmail.com', 587)
server.starttls()
server.login(username, password)

for i in range(len(emails)):
    msg = MIMEMultipart("alternative")
    msg['From'] = username
    msg['To'] = names[i]
    msg['Subject'] = Subject
    count = count + 1
    #     text = '''
    # Hello {},
    #     3 mails
    # '''.format(names[i])
    html_txt = """

<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style="font-size: 17px; font-family: Calibri, sans-serif;">Dear Sir / Miss</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style="font-family: Calibri, sans-serif;"><span style="font-size: 17px;">I would like to introduce our company&nbsp;<strong>SAEED NAVEED BROTHERS&nbsp;</strong></span></span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style="font-family: Calibri, sans-serif;"><span style="font-size: 17px;">SAEED NAVEED BROTHERS is a Veterinary Instruments, Farrier Tools, Equestrian Products Manufacturing and Export Company in Pakistan.</span></span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style="font-size: 17px; font-family: Calibri, sans-serif; color: rgb(226, 80, 65);">(Our Catalogs are Attached)</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><a href="https://drive.google.com/file/d/0B2ulnxsb2MfJTWVxaUZIWUtwQ2g3ZlJxT3J1X1cyRzJWS3Zr/view?usp=sharing" rel="noopener noreferrer" target="_blank">Veterinary Catalog</a></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style='font-family: "Calibri Light", sans-serif;'><a href="https://drive.google.com/file/d/0B2ulnxsb2MfJdHVPUjFfdHRjREE/view?usp=sharing" rel="noopener noreferrer" target="_blank">Main Catalog</a></span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><a data-mt-detrack-attachment-inspected="true" data-mt-detrack-inspected="true" data-saferedirecturl="https://www.google.com/url?q=https://drive.google.com/file/d/1WLG-WjHQ5ggaz8M3KiYOJXMcGdninIQC/view?usp%3Dsharing&source=gmail&ust=1598533441987000&usg=AFQjCNFdTDzrpae64l7B1TVxD1wB6CTT4Q" href="https://drive.google.com/file/d/1WLG-WjHQ5ggaz8M3KiYOJXMcGdninIQC/view?usp=sharing" rel="noopener noreferrer" style="color: rgb(17, 85, 204);" target="_blank">Our Banner</a></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style='font-family: "Calibri Light", sans-serif;'>&nbsp;</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style='font-family: "Calibri Light", sans-serif; font-size: 18px; text-align: inherit;'>A list of product categories include:</span></p>
<ul style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; list-style-type: disc;">
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Bits, Spurs, Stirrups</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Equestrian Health Products</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Veterinary Instruments</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Farrier Tools</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Hoof knives, Folding knives, Custom knives</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Tongs</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Clinchers, Adjustable Clinchers</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Hackamores</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Eggbutt Bits</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Cheek Mouth Pieces &nbsp;</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Castration Forceps</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Hoof Testers</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Pet Grooming Shears</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Equestrian Leather Products</span></span></li>
    <li style="margin-left: 15px;"><span style="font-size: 18px;"><span style='font-family: "Calibri Light", sans-serif;'>Riding Gloves &amp; Chaps</span></span></li>
</ul>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style='font-size: 16px; font-family: "Calibri Light", sans-serif;'>&nbsp;</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style='font-size: 17px; font-family: "Calibri Light", sans-serif;'>If you need any sample to check our quality. We will be happy to send it to you.</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style="font-size: 17px;"><span style='font-family: "Calibri Light", sans-serif;'>We do Business World Wide,&nbsp;</span></span><span style='font-size: 17px; font-family: "Calibri Light", sans-serif;'>looking forward to doing good business with you.</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><br></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style='font-size: 16px; font-family: "Calibri Light", sans-serif;'>Best regards</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif;"><span style="font-family: Garamond, serif; color: rgb(80, 0, 80);"><br><span style="font-size: 22px;">KHURRAM SAEED</span></span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 13px; font-family: Garamond, serif; color: rgb(80, 0, 80);">SALES DIRECTOR</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 13px; font-family: Arial, sans-serif; color: rgb(80, 0, 80);">&nbsp;</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; font-size: 15px; font-family: Calibri, sans-serif; background: white; line-height: 1;"><span style="font-size: 48px; font-family: Garamond, serif; color: rgb(68, 68, 68);">SAEED NAVEED BROTHERS</span><span style="font-size: 36px; font-family: Garamond, serif; color: rgb(68, 68, 68);">&nbsp;</span><span style="font-family: Garamond, serif; color: rgb(68, 68, 68); font-size: 24px;">LTD</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; font-size: 15px; font-family: Calibri, sans-serif; background: white; line-height: 1;"><span style="font-size: 14px; font-family: Garamond, serif; color: rgb(124, 112, 107);">MANUFACTURER &amp; EXPORTER OF VETERINARY INSTRUMENTS, EQUESTRIAN HARDWARE AND FARRIER TOOLS</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif; background: white;"><span style="font-size: 13px; font-family: Arial, sans-serif; color: rgb(80, 0, 80);">&nbsp;</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif; background: white;"><span style='font-family: "Courier New"; color: rgb(102, 102, 102);'>Gmail: &nbsp; &nbsp;&nbsp;<a data-mt-detrack-attachment-inspected="true" data-mt-detrack-inspected="true" href="mailto:snbrothers@gmail.com" style="color: rgb(17, 85, 204);" target="_blank"><span style="color: rgb(17, 85, 204);">snbrothers@gmail.com</span></a></span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif; background: white;"><span style='font-family: "Courier New"; color: rgb(102, 102, 102);'>Email: &nbsp; &nbsp;&nbsp;<a data-mt-detrack-attachment-inspected="true" data-mt-detrack-inspected="true" href="mailto:info@snbrothers.com" style="color: rgb(17, 85, 204);" target="_blank"><span style="color: rgb(17, 85, 204);">info@snbrothers.com</span></a><br>WhatsApp: &nbsp;+92 321 611 6509</span></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif; background: white;"><span style='font-family: "Courier New"; color: rgb(102, 102, 102);'>Phone: &nbsp; &nbsp; +92 52 355 4004</span></p>
<p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; background: white;"><span style='font-family: "Courier New"; font-size: 15px; color: rgb(102, 102, 102); text-align: inherit;'>YouTube: &nbsp;&nbsp;</span><a data-mt-detrack-attachment-inspected="true" data-mt-detrack-inspected="true" data-saferedirecturl="https://www.google.com/url?q=https://www.youtube.com/user/snbrothers&source=gmail&ust=1598533441987000&usg=AFQjCNGBxC6Y9EY4CktNjChtxzpOBl19xA" href="https://www.youtube.com/user/snbrothers" style='color: rgb(17, 85, 204); font-family: "Courier New"; font-size: 15px; text-align: inherit;' target="_blank">https://www.youtube.com/<wbr>user/snbrothers</a><span style='font-family: "Courier New"; font-size: 15px; color: rgb(102, 102, 102); text-align: inherit;'>&nbsp;</span></p>
<p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; background: white;"><span style="font-size: 15px;"><span style='font-family: "Courier New", courier; color: rgb(124, 112, 107);'>Instagram</span>: &nbsp;</span><a data-mt-detrack-attachment-inspected="true" data-mt-detrack-inspected="true" data-saferedirecturl="https://www.google.com/url?q=https://www.instagram.com/snb.company.1971/&source=gmail&ust=1598533441987000&usg=AFQjCNELcdMg1cH4ZHCSzW9K2wFjdSs16w" href="https://www.instagram.com/snb.company.1971/" style='color: rgb(102, 102, 102); font-family: "Courier New"; font-size: 15px;' target="_blank">https://www.instagram.com/<wbr>snb.company.1971/</a><br><span style="font-size: 15px;"><span style='font-family: "Courier New", courier; color: rgb(124, 112, 107);'>Facebook</span>: &nbsp;</span><a data-mt-detrack-attachment-inspected="true" data-mt-detrack-inspected="true" data-saferedirecturl="https://www.google.com/url?q=http://www.facebook.com/saeednaveedbrothers&source=gmail&ust=1598533441987000&usg=AFQjCNEKpWXl2xbbYYUBx77zNUCbPxgGSQ" href="http://www.facebook.com/saeednaveedbrothers" style='color: rgb(102, 102, 102); font-family: "Courier New"; font-size: 15px;' target="_blank"><span style="color: rgb(17, 85, 204);">www.facebook.com/<wbr>saeednaveedbrothers</span></a><br><span style="font-size: 15px;"><span style='font-family: "Courier New", courier; color: rgb(124, 112, 107);'>Alibaba</span>: &nbsp;&nbsp;</span><a data-mt-detrack-attachment-inspected="true" data-mt-detrack-inspected="true" data-saferedirecturl="https://www.google.com/url?q=http://www.snbrothers.trustpass.alibaba.com/&source=gmail&ust=1598533441987000&usg=AFQjCNEeMMhltYG1-cDYadNOaZOJRfiKbg" href="http://www.snbrothers.trustpass.alibaba.com/" style='color: rgb(102, 102, 102); font-family: "Courier New"; font-size: 15px;' target="_blank"><span style="color: rgb(17, 85, 204);">www.snbrothers.trustpass.<wbr>alibaba.com</span></a></p>
<p style="color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; line-height: normal; font-size: 15px; font-family: Calibri, sans-serif; background: white;"><span style='font-family: "Courier New"; color: rgb(102, 102, 102);'>Address: &nbsp; P.O. Box 1322, 11c Nishter Road, SIE, Sialkot-51310 (Pakistan)</span></p>



        """
    # part_1 = MIMEText(text, 'plain')
    part_1 = MIMEText(html_txt, 'html')
    # msg.attach(part_1)
    msg.attach(part_1)
    # with open('logo.png', 'rb') as attach_file:
    #     image_name = attach_file.name
    #     image_type = imghdr.what(attach_file.name)
    #     image_data = attach_file.read()
    # message.add_attachment(image_data, maintype="image", subtype=image_type, filename=image_name)
    # part_1 = MIMEText(text, 'plain')
    part_2 = MIMEText(html_txt, 'html')
    # msg.attach(part_1)
    msg.attach(part_2)
    message = msg.as_string()
    # with open('logo.png', 'rb') as attach_file:
    #     image_name = attach_file.name
    #     image_type = imghdr.what(attach_file.name)
    #     image_data = attach_file.read()
    # message.add_attachment(image_data, maintype="image", subtype=image_type, filename=image_name)

    server.sendmail(username, emails[i], message)
    print(count, '. Mail sent to', emails[i])
    time.sleep(30)

server.quit()
print('All emails sent successfully!')
